### ISSUE TITLE
Error in visualize (possibly) due to color_function scaling and histogram creation

### ISSUE THREAD

**Issue by emerson-escolar** [MLWave/kepler-mapper#120]
Hi everyone, 

I've been using kepler-mapper for analyzing some data, and found that certain choices of the color_function in mapper.visualize causes an error or incorrect output.

**To Reproduce**
The following is a minimal working example of the bug.
```
import kmapper as km
import numpy as np
import sklearn
data = np.array([[0],[1]])
lens = data
colorf = np.array([[1],[6]])
mapper = km.KeplerMapper()
graph = mapper.map(lens, data, clusterer=sklearn.cluster.DBSCAN(eps=0.1, min_samples=0),
                   coverer=km.Cover(nr_cubes=2, overlap_perc=0.2))
mapper.visualize(graph, color_function=colorf,path_html="test.html")
```
which produces the following message (directories truncated)
```
kepler-mapper/kmapper/visuals.py:93: RuntimeWarning: invalid value encountered in long_scalars
  height = int(((bar / max_bucket_value) * 100) + 1)
Traceback (most recent call last):
  File "bug.py", line 12, in <module>
    mapper.visualize(graph, color_function=colorf,path_html="test.html")
  File "kepler-mapper/kmapper/kmapper.py", line 514, in visualize
    lens_names, custom_tooltips, env)
  File "kepler-mapper/kmapper/visuals.py", line 62, in format_mapper_data
    tt = _format_tooltip(env, member_ids, custom_tooltips, X, X_names, lens, lens_names, color_function, node_id)
  File "kepler-mapper/kmapper/visuals.py", line 207, in _format_tooltip
    histogram = build_histogram(color_function[member_ids])
  File "kepler-mapper/kmapper/visuals.py", line 93, in build_histogram
    height = int(((bar / max_bucket_value) * 100) + 1)
ValueError: cannot convert float NaN to integer
```
**System details**
 - OS: macOS Mojave 10.14
 - Python 3.7.0 via Homebrew
 - scikit-learn 0.20.0 from PyPI
 - numpy 1.15.3 from PyPI
 - kepler-mapper installed from source (master)

**My guess** 
I did some digging, and found that the error probably originates from here:
https://github.com/MLWave/kepler-mapper/blob/d640181bac67269b884186e038b3dec09705ef2c/kmapper/visuals.py#L84-L85
where the returned value `hist` is an array containing only 0's. This causes the "cannot convert float NaN to integer" ValueError as we divided by max_bucket_value, which is 0.

As to why `hist` can sometimes be a zero array:
First of all, color_function is scaled by MinMaxScaler to be in the range (0,1) by
https://github.com/MLWave/kepler-mapper/blob/d640181bac67269b884186e038b3dec09705ef2c/kmapper/visuals.py#L29-L30
However, it seems that due to floating point computation, the largest value is not scaled to exactly 1 (and may sometimes exceed it). The largest value of 6 in the MWE color_function is scaled to something like 1.0000000000000002, which falls outside [0,1].

Note that even if hist were not the zero array, the largest value of the color_function being excluded is a possibility due to this scaling and the assumption that it falls neatly within h_min=0 and h_max=1. When this happens, the resulting histogram will be incorrect but no error will be reported.

**Comment by sauln** [comment]
Thank you for the detailed bug report and leads on the problem.  Your guess sounds like a likely culprit.  

Do you have any ideas on how to fix it? Maybe adding a small buffer to the histogram range? 

 I'll try to look into soon, but a pull request would be very appreciated 👍 

Thank you!

**Comment by emerson-escolar** [comment]
Thanks for the reply. 

I noticed that master was updated recently. Running the same MWE again, it's no longer an error but a warning. The current version uses np.floor instead of int to get `height`
https://github.com/MLWave/kepler-mapper/blob/fe1d0e44e711452b409fba96ab6b2493e1c46a68/kmapper/visuals.py#L225
which only gives a warning when the described bug happens:
```
kepler-mapper/kmapper/visuals.py:225: RuntimeWarning: invalid value encountered in long_scalars
  height = np.floor(((bar / max_bucket_value) * 100) + 0.5)
kepler-mapper/kmapper/visuals.py:226: RuntimeWarning: invalid value encountered in long_scalars
  perc = round((bar / sum_bucket_value) * 100., 1)
```
with essentially the same incorrectness in the output histogram.

I made a fork with my proposed fix, which is to change all values greater than 1 in color_function to 1, after MinMaxScaler. It's not a very elegant solution though..

**Comment by emerson-escolar** [comment]
It's my first pull request ever so if I'm doing this wrong please tell me 😄
